spring:
  main:
    # This program is not web application
    web-application-type: none
  # Elasticsearch connection configurations
  elasticsearch:
    rest:
      uris: "http://localhost:9200"
      username: "elastic"
      password: "MyPw123"

logging:
  level:
    io.omnipede.data.didpipeline: debug