networks:
  warehouse:
    driver: bridge

services:

  # Pipeline process
  pipeline:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: did-pipeline
    image: didpipeline:latest
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "10"
    # Start pipeline only when elasticsearch process starts up
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - warehouse

  # Elastic search 설정
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    # Elastic search 계정정보
    environment:
      discovery.type: single-node
      xpack.security.enabled: "true"
      xpack.security.transport.ssl.enabled: "true"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "MyPw123"
    networks:
      - warehouse
    # Elasticsearch http server health check
    healthcheck:
      test: ["CMD-SHELL", "curl -X GET http://localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 10

  # Kibana 설정
  kibana:
    container_name: kibana
    image: kibana:7.10.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - warehouse